name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build
        run: dotnet build src --no-restore

      - name: Test
        run: dotnet test src --no-build --verbosity normal
        env:
          SIGNICAT_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SIGNICAT_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}